name: Bump version of packages

on:
  pull_request:
    branches: main
    types: [labeled, synchronize]
  workflow_dispatch:
    inputs:
      type:
        description: |
          The SemVer type <major|minor|patch> to use manually by
          overriding the label type
        required: false
      name:
        description: |
          The package name to use when running manually. If not specified, it will
          be determined by looking at the closest package.json to the first changed
          file.
        required: false
      summary:
        description: The changeset summary to use when running manually.
        required: false

jobs:
  changeset:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Debug Labels
        run: echo "${{ toJson(github.event.pull_request.labels) }}"
      - name: Checkout in the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
