name: Release the changes of the documentation to github pages

on:
  push:
    branches: main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  github-page:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout in the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install

      - name: Build Docs
        run: pnpm build --filter=@thanka-digital/beej-component --filter=@beej/docs

      - name: Upload artifcats
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/docs/build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
